version: '3.8'

services:
  app:
    build: .
    container_name: vt-mapas-app
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./data:/var/www/html/data
